apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zj12t0g10-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zj12t0g10-java-quarkus-gitops